global:
  scrape_interval: 1m
  evaluation_interval: 2m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'basicwebserver'
    scrape_interval: 20s
    static_configs:
      - targets: ['my-running-app:3333']